modLoader = "javafml"
loaderVersion = "[35,)"
license = "MIT"

[[mods]]
modId = "glowing_fire_glow"
version = "${version}"
displayName = "GlowingFireGlow"
#displayURL="http://example.com/"
#logoFile="GlowingFireGlow.png"
#credits="Thanks for this example mod goes to Java"
authors="til"
description = '''

'''

[[dependencies.glowing_fire_glow]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.glowing_fire_glow]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,1.17)"
ordering = "NONE"
side = "BOTH"
